substitutions:
  _REGION: asia-east1
  _REPOSITORY: student-news
  _TAG: manual

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - publisher/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/student-news-publisher:${_TAG}
      - .

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/student-news-publisher:${_TAG}
